name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  secret-scan:
    permissions:
      contents: read
      security-events: write   # Add this line to grant the nested job write permissions
    uses: FayezMadi/ghactionscourse/.github/workflows/secret-scan.yml@main
